// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/socket.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/node.tsx";
import * as $$0 from "./islands/Negotiate.tsx";
import * as $$1 from "./islands/State.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/socket.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/node.tsx": $4,
  },
  islands: {
    "./islands/Negotiate.tsx": $$0,
    "./islands/State.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
